# Generated by Django 3.2.5 on 2021-10-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_fname', models.CharField(max_length=100)),
                ('client_lname', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=100)),
                ('client_password', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=100)),
                ('client_vehicle_capacity', models.IntegerField()),
                ('client_available_vehicle_capacity', models.IntegerField()),
                ('client_latitude', models.FloatField()),
                ('client_longitude', models.FloatField()),
                ('client_landmark', models.CharField(max_length=100)),
                ('client_created_date', models.DateTimeField(auto_now_add=True)),
                ('client_modified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=100)),
                ('user_lname', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=100)),
                ('user_vechicle_type', models.CharField(max_length=100)),
                ('user_vechicle_number', models.CharField(max_length=100)),
                ('user_created_date', models.DateTimeField(auto_now_add=True)),
                ('user_modified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
