# Generated by Django 3.2.5 on 2021-10-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_parking_Price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
