# Generated by Django 3.2.5 on 2021-10-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_client_parking_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
